/**
 * ****************************************************************************
 * loc.c: Definitions
 * SPDX-License-Identifier: Apache-2.0
 * Copyright (c) 2024 Aditya P. Gurajada
 *
 * History:
 *  3/2024  - Original version provided by Charles Baylis
 * ****************************************************************************
 */
#include <stdio.h>

/*
 * Define the -I<path> to pick-up include/loc.h ; You cannot include the
 * loc.h generated by the Python script, that provides another technique
 * to generate the LOC-encoding.
 */
#include "loc.h"

/**
 * A dummy location ID used as reference point within the loc_ids section.
 * All location ids are stored as an offset from this variable.
 */
#if __APPLE__
LOC Loc_id_ref __attribute__((section("__DATA, loc_ids")));
#else
LOC Loc_id_ref __attribute__((section("loc_ids")));
#endif  // __APPLE__

/**
 * Decode the LOC-ID and print code-location details.
 */
void
loc_print(loc_t id)
{
   LOC *loc = (struct location *)(((intptr_t)&Loc_id_ref) + id);
   printf("Location is in function '%s', %s:%d\n",
          loc->func, loc->file, loc->line);
}
