on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    #! python-app.yml actually runs Py-tests. But test.sh also invokes
    #! them (by default; some duplication). So install reqd s/w up front.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    #! - name: configure
    #!  run: ./configure

    - name: clean
      run: make clean

    - name: make-all
      run: CC=gcc LD=gcc make

    #! Execute testing targets; Run py-test and LOC-enabled sample programs
    - name: make-tests-verbose
      run: CC=gcc LD=gcc BUILD_VERBOSE=1 make run-tests run-test-code

    #! - name: Run check
    #!   run: make check

    #! - name: Run distcheck
    #! run: make distcheck
