name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #! - name: configure
    #!  run: ./configure

    - name: clean
      run: make clean

    - name: make
      run: CC=gcc LD=gcc make

    #! - name: Run check
    #!   run: make check

    #! - name: Run distcheck
    #! run: make distcheck
